###### Database Properties ######
spring:
  datasource:
    url : ${db_url}
    username: ${db_user}
    password: ${db_pass}
    driver-class-name: com.mysql.cj.jdbc.Driver

  ###### Email Properties ######
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: ${mail_user}
#    password: ${mail_pass}
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true

  ####### Hibernate Properties #######
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update